begin transaction;
create table commands(name varchar(100) primary key, message varchar(100), type varchar(10));
insert into commands(name, message, type) values("taco", "taco taco.. TACO!!", "message");
insert into commands(name, message, type) values("handsomepants", "%s puts on a pair of handsome pants and does a little boogie dance", "message");
insert into commands(name, message, type) values("toke", "%s takes a big toke", "message");
insert into commands(name, message, type) values("psychotica", "%s goes psycho with psychotica", "message");
insert into commands(name, message, type) values("cartis^", "what is the ^ even for?", "message");
insert into commands(name, message, type) values("sullengenie", "%s rubs the magic lamp hoping for a wish, but the genie is too sullen", "message");
insert into commands(name, message, type) values("emer1cah", "emer1cah, Fuck Yeah! Comin' again to save the motherfuckin' day, yeah!", "message");
insert into commands(name, message, type) values("tickle", "ties %s up to the bedpost tightly and takes out a feather. Time for some tickles!", "action");
insert into commands(name, message, type) values("lick", "jumps on top of %s and gives them a big slobbery lick!", "action");
insert into commands(name, message, type) values("peck", "sneaks up on %s and delicately pecks them on the cheek", "action");
insert into commands(name, message, type) values("paint", "pulls out the paint set as %s lays naked on the couch posing", "action");
insert into commands(name, message, type) values("landlust", "lusts %s!", "action");
insert into commands(name, message, type) values("beer", "goes to the fridge, grabs a fresh bottle, pops the cap off and hands it to %s. Enjoy!", "action");
insert into commands(name, message, type) values("shuggle", "shuggles %s!", "action");
insert into commands(name, message, type) values("pinch", "sneaks behind %s and gives a little pinch on the butt!", "action");
insert into commands(name, message, type) values("snuggle", "curls up next to %s and snuggles closely", "action");
insert into commands(name, message, type) values("pillowfight", "waits until they are sleeping and SMOTHERS %s WITH A PILLOW!", "action");
insert into commands(name, message, type) values("encourage", "cheers %[1]s on. GOOOOOO %[1]s! YOU GOT DIS!", "action");
insert into commands(name, message, type) values("bearhug", "opens the bear cage and watches as %s gets mauled! AWW! What a big hug!", "action");
insert into commands(name, message, type) values("pat", "pats %s on head, good jooob!", "action");
insert into commands(name, message, type) values("defenestrate", "tosses %s out the window!", "action");
insert into commands(name, message, type) values("pie", "throws a pie in %s's face! Such comedy!", "action");
commit;
